controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


arm_controller:
  ros__parameters:
    command_interfaces:
        - position
    state_interfaces:
        - position
        - velocity
    joints:
        - Joint_1
        - Joint_2
        - Joint_3
    state_publish_rate: 25.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      Joint_1:
        trajectory: 0.05
        goal: 0.03
