controller_names:
    - arm_controller

arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - Joint_1
        - Joint_2
        - Joint_3
